[package]
name = "cput"
version = "0.1.0"
authors = ["Mehrdad Arshad Rad <arshad.rad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
tokio = { version = "0.2", features = ["full"] }
